[ERROR] 2022-06-13 22:39:52,474 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "2020-05-11 20:30:02.536647",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Lead",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 91, in add_code
    path = os.path.join(get_module_path(self.module), 'doctype', scrub(self.name))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/utils.py", line 166, in get_module_path
    return frappe.get_module_path(module)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 886, in get_module_path
    return get_pymodule_path(local.module_app[module] + "." + module, *joins)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 908, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 870, in get_module
    return importlib.import_module(modulename)
  File "/home/ubuntu/frappe-bench/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.crm'
[ERROR] 2022-06-13 22:39:52,700 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2022-06-13 22:39:52.476021-127.0.0.1-635
[ERROR] 2022-06-13 22:40:02,335 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "2020-05-11 20:30:02.536647",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Lead",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 91, in add_code
    path = os.path.join(get_module_path(self.module), 'doctype', scrub(self.name))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/utils.py", line 166, in get_module_path
    return frappe.get_module_path(module)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 886, in get_module_path
    return get_pymodule_path(local.module_app[module] + "." + module, *joins)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 908, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 870, in get_module
    return importlib.import_module(modulename)
  File "/home/ubuntu/frappe-bench/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.crm'
[ERROR] 2022-06-13 22:40:02,383 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2022-06-13 22:40:02.338096-127.0.0.1-9f3
[ERROR] 2022-06-13 22:40:23,724 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Contact\",\"name\":\"Nuevo Contacto 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"sync_with_google_contacts\":0,\"status\":\"Passive\",\"pulled_from_google_contacts\":0,\"is_primary_contact\":0,\"unsubscribed\":0,\"first_name\":\"123\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 905, in run_before_save_methods
    self.run_method("validate")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 806, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1082, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1096, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 870, in get_module
    return importlib.import_module(modulename)
  File "/home/ubuntu/frappe-bench/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.crm'
[ERROR] 2022-06-13 22:40:23,841 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2022-06-13 22:40:23.725755-127.0.0.1-4d7
